### ISSUE TITLE
could not load: libzip(|2|4).dylib

### ISSUE THREAD

**Issue by rsirres** [nim-lang/zip#19]
My Machine:
```
ProductName:	Mac OS X
ProductVersion: 10.9.5
```

My Code:
```
import zip/zipfiles
```

Results in:
```
dlopen(libzip.dylib, 2): image not found
dlopen(libzip2.dylib, 2): image not found
dlopen(libzip4.dylib, 2): image not found
could not load: libzip(|2|4).dylib
Error: execution of an external program failed
```

**Comment by dom96** [comment]
Do you have libzip installed?

**Comment by rsirres** [comment]
No. Is it possible to add libzip as nimble dependency?

**Comment by dom96** [comment]
Nimble cannot install this dependency for you. You can only get it to give you a hint (docs for this feature are available here: https://github.com/nim-lang/nimble#external-dependencies).

PRs to add this to zip.nimble are welcome.

**Comment by yatesco** [comment]
I think I might be having a similar problem, but adding `libzip` as a foreign dependency didn't help. More details: https://forum.nim-lang.org/t/4108
