### ISSUE TITLE
Zlib tests fail: zlib version mismatch!

### ISSUE THREAD

**Issue by Krognol** [nim-lang/zip#23]
`echo`ing `zlibVersion` gives me `1.2.8`.

Running
Nim 0.17.0
Windows 10

**Comment by Krognol** [comment]
Works fine on my linux vm. I guess my zlib version is outdated? Where does Nim even look for .dll's?

**Comment by fabianallendorf** [comment]
Is there a way to fix this yet? I have the exact same problem. Even when I download a newer zlib version, it errors with `could not load zlib1.dll`

**Comment by dom96** [comment]
@PapaNoah that seems like a different error. Are you sure the DLL's architecture matches your executable? (the DLL could be 64 bit whereas your exe is 32 bit).

**Comment by fabianallendorf** [comment]
@dom96 It's true, i've tried it with 32 bit dlls apparently. However, each 64bit zlib version from 1.2.7 up to 1.2.11 produces the version error. I'm not really into this issue but judging from the [zlib doc](http://refspecs.linuxbase.org/LSB_3.0.0/LSB-PDA/LSB-PDA/zlib-deflateinit2.html), this may have something to do with z_stream size difference.

> Z_VERSION_ERROR: The version requested is not compatible with the library version, or the z_stream size differs from that used by the library.

**Comment by PMunch** [comment]
I'm getting this same error using Arch Linux and zlib 1.2.11, Nim 0.20.0.

**Comment by snej** [comment]
Same as #39 and #53. The error is because the ZStream struct is badly defined and has the wrong size on LP64 OSs.
