### ISSUE TITLE
Error: ambiguous identifier: 'Time'

### ISSUE THREAD

**Issue by juancarlospaco** [nim-lang/zip#47]
```
zip-0.2.1/zip/libzip.nim(71, 13) Error: ambiguous identifier: 'Time' -- use one of the following:
  posix.Time: Time
  times.Time: Time
```

- Code imports `posix` and `times`.
- https://github.com/nim-lang/zip/blob/master/zip/libzip.nim#L71

#### Workaround

```nim
import posix except Time  # On the code that uses zip
```
:slightly_smiling_face:

**Comment by dom96** [comment]
PR?

**Comment by dom96** [comment]
This seems like a breaking Nim change though. @Araq?

**Comment by Araq** [comment]
@dom96 Looks to me the compiler previously accepted wrong code and the compiler got fixed.

**Comment by Araq** [comment]
I dunno, need to investigate.
