### ISSUE TITLE
Unable to import module

### ISSUE THREAD

**Issue by telatin** [nim-lang/zip#61]
Hello,
I installed the module via `nimble install zip` (both from macOS and Ubuntu 16.04), and the process gave no error (installed zip@0.3.1 and ended with _zip installed successfully_).

When trying to compile a simple:
```nim
import zip/zipfile
```
i get this error:
```
/[...]/testarchive.nim(2, 11) Error: cannot open file: zip/zipfile
```
---
On Ubuntu I tried downloading the repository and testing manually with `nimble task tests`, and they pass from the cloned repo.

Can you provide some guidance on this error? Thanks

**Comment by narimiran** [comment]
From my quick search, the file has a plural name (with the `s` in the end): `zipfiles`.

Can you try to do `import zip/zipfiles` and see if it works?

**Comment by telatin** [comment]
Silly me!
Thanks!
